# docker-compose.yml

version: '3.8'

services:
  vpn_bot:
    build: .
    container_name: vpn_telegram_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs